### PR TITLE
popup closing button: centering label

### PR DESCRIPTION
**Pull request by plugn**
this makes `close-button`'s label centered

### CODE REVIEW

**Comment by Turbo87** [comment]
could you be a bit more verbose on what this changes and why?

**Comment by plugn** [comment]
please tale a look at closing button with a border:
https://i.gyazo.com/d8849b7cde9233c5dc12c13a569d29e1.png

I assumed that `font-size: 25pt` was a mistype because of `font-size: 25px` looks better:
https://i.gyazo.com/11b3f7dfa63919766001eb8238db3009.png

**Comment by Turbo87** [comment]
ah, that sounds about right. thanks!

**Comment by plugn** [comment]
my pleasure :)

**Pull request merged**
