### PR TITLE
allow setContent() to accept HTML DOM element object

### PR DESCRIPTION
**Pull request by haoliangyu**
This pull request allows setContent() to accept HTML DOM element object as input. It would provide convenience to render dynamically compiled content, especially for those whose HTML element isn't generated immediately (like [Angular](http://stackoverflow.com/questions/26660495/can-i-get-the-compiled-html-of-an-angular-element)).

### CODE REVIEW

**Comment by Turbo87** [comment]
I'm not sure how I feel about this... how do you use this in angular?

side note: indentation is inconsistent

**Comment by haoliangyu** [comment]
In angular we are able to bind data and events to a plain html dynamically with the [$compile](https://docs.angularjs.org/guide/directive) process, like

``` javascript
// Suppose I have defined a directive <my-directive> with some html template inside
var html = '<my-directive></my-directive>';

// Scope is an object in angular specifically used as controller and data storage.
// Generally we will use the data of the scope to manipulate and update the DOM element
var scope = $rootScope.$new(true);
scope.data = data;

// Here the html is compiled with the scope, which will generate its internal dom tree.
// This will return the entire dom element.
var dom = $compile(html)(scope)[0];

// Hopefully I can get the outer HTML and use the setContent() method
// sidebar.setContent(dom.outerHTML);

// However, after the $compile() is called, it will not immediately take effect until 
// the next digest circle. Since it doesn't work at the moment I call, I will get an 
// empty string if I try to get outerHTML immediately. So rather than using $timeout to
// wait for its working, directly passing the DOM element and letting it go is a more
// convenient solution.
sidebar.setContent(dom);
```

I am not sure if you are familiar with Angular so I elaborate it a bit. Please let me know if it's not clear for you :)

source: [Can I get the compiled html of an Angular element?](http://stackoverflow.com/questions/26660495/can-i-get-the-compiled-html-of-an-angular-element)

**Comment by Turbo87** [comment]
I've touched Angular and if you look at my profile you'll probably see that I prefer another framework :wink: 

I've never been a big fan of the `setContent()` method in general, but if you don't see another way to do this then I'm fine with merging this. I assume you tested that passing in strings still works as expected?

**Comment by haoliangyu** [comment]
@Turbo87 Yes! I have tested it with some examples and it works well with the plain HTML text.

**Pull request merged**
